spring.application.name=titu

# Configuracao do Banco de Dados (Docker)
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/SaaS_Manager}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:123456}
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuracao do JPA (Pra ele criar as tabelas sozinho)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# Cache de imagens, CSS e JS (Salva no navegador do cliente por 1 ano)
spring.web.resources.cache.period=31536000